name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build book
        env:
          VERSION: 0.1.${{ github.run_number }}
        run: |-
          npm install -g md-to-pdf
          for f in *.md; do cat $f; echo; done | md-to-pdf --stylesheet "theme/style.css" > root.pdf
          mkdir -p _output
          ls
          mv root.pdf _output
          cd _output
          ls

      # - name: Build book
      #   env:
      #     VERSION: 0.1.${{ github.run_number }}
      #   run: |-
      #     npm install -g md-to-pdf
      #     md-to-pdf --stylesheet "theme/style.css" root.md
      #     mkdir _output
      #     ls
      #     mv root.pdf _output
      #     cd _output
      #     ls
      
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: _output